#+title: doom emacs config
#+author: Javier Castilla
#+EMAIL: jcastp@pm.me
#+language: en
* Summary
This is the literate configuration for my doom emacs use cases.

I will try to document and compartmentalize the sections, so it's easier to follow up, but it won't always be possible, as some functions overlap, and I'm usually a messy person when speaking of testing.

* General
** emacs lisp lexical binding
#+begin_src emacs-lisp :tangle yes
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

** variable definition
I define here some very basic variables to configure several parts of the config.

*** Directories used by emacs
#+begin_src emacs-lisp
(defvar my-config-dir "~/.doom.d/"
  "Personal config directory.")

(defvar my-data-dir "~/Nextcloud/config/.emacs.d/"
  "Personal data directory.")
#+end_src

*** Machine names
#+begin_src emacs-lisp
;; working laptop vm
(defvar my-worksystem-p (equal (system-name) "lubuntuwork")
  "Name of my working machine.")

;; My desktop machine, able to run anything
(defvar my-desktopsystem-p (or
			    (equal (system-name) "olimpo")
			    (equal (system-name) "doomslayer"))
  "Names of my personal machines.")

;; Writing machines
;; probably we can strip some features from them, as they are low end machines
(defvar my-writinglaptop-p (or
			    (equal (system-name) "argos")
			    (equal (system-name) "caliope"))
  "Names of my writing laptops.")
#+end_src

*** Environments
#+begin_src emacs-lisp
(defvar my-homeenvironment-p (or
			      (string= (getenv "WORKING") "HOME")
			      (not (string= (getenv "WORKING") "WORK")))
  "My home environment predicate.")

(defvar my-workenvironment-p (string= (getenv "WORKING") "WORK")
  "My work environment predicate.")
#+end_src

*** Encrypted data directories
#+begin_src emacs-lisp
;; define my clear directory
(defvar my-clear-directory (expand-file-name "Nextcloud_claro/gocryptfs_claro" (getenv "HOME"))
  "My decrypted directory.")

;; check the directory exists
;;(file-directory-p my-clear-directory)

;; check if a directory is a mount point - against "mount" command in the OS.
(defun is-mount-point-p (path)
  "Check if the given PATH is a mount point."
  (let ((mount-output (shell-command-to-string "mount")))
    (string-match (regexp-quote path) mount-output)))

;; This variable will control if my encrypted dir is mounted on the clear directory
(defvar my-clear-directory-is-mounted-p 0
  "My clear directory is correctly mounted - predicate.")

;; Check if the directory is mounted
(if (is-mount-point-p my-clear-directory)
    ;; if it is mounted, we change the variable
    (setq my-clear-directory-is-mounted-p t)
  ;; if it is not mounted, then we should launch the script here
  (progn
    ;; I think we should not launch this from here, but just examine what is wrong in the OS.
    ;;(shell-command "bash ~/Nextcloud/config/mount-encrypted-dirs.sh")
    )
  )
#+end_src

** Personal information
Based on the environment variables.

This uses a special file, not commited, with my personal information, located in the path below.
It contains the variables =user-full-name= and =user-mail-address=
#+begin_src emacs-lisp
;; to protect my personal information, this file is not commited
(load (expand-file-name "personal_info.el" my-data-dir))
#+end_src

** Start with a maximized frame
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src
** Save command history
It is nice to have commands and their history saved so that every time you get back to work, you can just re-run stuff as you need it. It isn't a radical feature, it is just part of a good user experience.

#+begin_src emacs-lisp
(setq savehist-file (expand-file-name "savehist" my-data-dir))
(savehist-mode 1)
(setq history-length t)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history 1)
(setq savehist-additional-variables
      '(kill-ring
        search-ring
        regexp-search-ring)
      )
#+end_src

** recent files location
Configure where we save the recent files opened, so I don't loose them once I reinstall doom emacs.
#+begin_src emacs-lisp
;; where to store the recent list file
(after! recentf
  (setq recentf-save-file (expand-file-name "recentf" my-data-dir)))
#+end_src
** persp-save location
#+begin_src emacs-lisp
(use-package! persp-mode
  :config
  (setq persp-save-dir (expand-file-name "persp-confs/" my-data-dir))
)
#+end_src

** auto revert mode
When a file is changed in disk, the buffer reloads to reflect that change.
#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src
** dired config
*** dired omit mode disabled
I want to see all the files in the directory.
#+begin_src emacs-lisp :tangle yes
(remove-hook 'dired-mode-hook 'dired-omit-mode)
#+end_src
** Bookmarks
All the config related to the bookmarks.

#+begin_src emacs-lisp
(setq bookmark-default-file (expand-file-name "bookmarks" my-data-dir))
(setq bookmark-save-flag 1)  ;save bookmarks to .emacs.bmk after each entry
#+end_src
** Abbreviation mode
Defines a set of abbreviations that permits complete words with just some characters.

#+begin_src emacs-lisp
;;where do we read the abbrevs from
(setq abbrev-file-name (expand-file-name "abbrev_defs" my-data-dir))
(setq-default abbrev-mode t)
;; save abbrevs when files are saved
(setq save-abbrevs 'silently)
#+end_src
** electric pair mode
To automatically close parenthesis and other punctuation signs.

#+begin_src emacs-lisp
(electric-pair-mode 1)
;; make electric-pair-mode work on more sets of punctuation signs.
(setq electric-pair-pairs
      '(
        (?\¡ . ?\!)
        (?\¿ . ?\?)
        )
      )

(setq electric-pair-inhibit-predicate
      `(lambda (c)
         (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c)))
      )
      #+end_src
** set firefox or librewolf as the default browser
Setting firefox or librewolf as the default browser for opening http/s links.
#+begin_src emacs-lisp
  (setq librewolf_path "/usr/bin/librewolf")
  ;; check if librewolf is installed
  (if (file-exists-p librewolf_path)
       (progn
         (setq browse-url-firefox-program "librewolf")
         (setq browse-url-browser-function 'browse-url-firefox))
    ;; if no librewolf installed, we fall back to firefox
     (progn
       (setq browse-url-firefox-program "firefox")
       (setq browse-url-browser-function 'browse-url-firefox)))
#+end_src

* Evil customizations
** evil-escape
Instead of hitting ESC, that is outside my normal home reach, we will use a key chord for it.

#+begin_src emacs-lisp :tangle packages.el
(package! evil-escape)
#+end_src

I will use this chord to mark escape.
#+begin_src emacs-lisp :tangle yes
(evil-escape-mode)
(setq-default evil-escape-key-sequence "jk")
#+end_src
* UI
** Time and date
Put time and date on the status line

#+begin_src emacs-lisp
(setq display-time-day-and-date t
      display-time-24hr-format t)
(display-time)
#+end_src

** full path in the title bar
Put the complete path on the title bar, along the filename.

#+begin_src emacs-lisp
(setq-default frame-title-format "%b - (%f)")
#+end_src

** Battery management
On laptops it's nice to know how much power you have.

#+begin_src emacs-lisp
(unless (string-match-p "^Power N/A" (battery))
  (display-battery-mode 1)
  )
#+end_src

** Parens mode global
To show matching parens in all the buffers and modes.

#+begin_src emacs-lisp
(show-smartparens-global-mode 1)
#+end_src
** TODO ace-window
To better manage more buffers in screen, as seen here: https://github.com/abo-abo/ace-window

Used in the hydra snippets.
#+begin_src emacs-lisp
(use-package! ace-window
  :config
  (setq aw-scope 'frame)
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
  ;; (global-set-key (kbd "M-o") 'ace-window)
  ;; make the characters bigger, so it is easy to see
  (custom-set-faces
   '(aw-leading-char-face
     ((t (:inherit ace-jump-face-foreground :height 3.0)))))
  )
#+end_src

** dimmer
I want to differentiate the window I'm working with.

#+begin_src emacs-lisp :tangle packages.el
(package! dimmer
  :recipe (:host github :repo "gonewest818/dimmer.el"))
#+end_src

#+begin_src emacs-lisp
;;(dimmer-configure-which-key)
(dimmer-mode t)
(dimmer-configure-magit)
(dimmer-configure-org)

;; configure the dimmer
(setq dimmer-adjustment-mode :both)
(setq dimmer-fraction 0.3)
#+end_src

** avy can select from any window
To make avy able to select from any window in sight. This allows to change from one window to another in just one step.
#+begin_src emacs-lisp :tangle yes
(setq avy-all-windows t)
#+end_src

** avy keyconfig for goto line
I want to map the avy jump functions to some doom emacs keybindings.

#+begin_src emacs-lisp :tangle yes
(map! :after evil-easymotion
      :map evilem-map
      "l" #'evil-avy-goto-line)
#+end_src

** Open indirect buffer
Open a branch into a different frame, but the same buffer:

#+begin_src emacs-lisp
;; this is done to open the indirect buffer in another window
;; instead on the main one
(use-package! org
  :config
  (setq org-indirect-buffer-display 'other-window)

  (defun my/org-tree-open-in-right-frame ()
    "Open the subtree in a dedicated buffer."
    (interactive)
    (org-tree-to-indirect-buffer)
    ;;(windmove-right)
    (other-window 1) ;; to move to the newly generated window
    )

  (map! :leader
        :desc "Open org tree to indirect buffer"
        "8" #'my/org-tree-open-in-right-frame)
  )
  #+end_src
** visual fill column
https://github.com/joostkremers/visual-fill-column
This mode restricts the lines up until a set margin, and wraps them logically at that point.

#+begin_src emacs-lisp :tangle yes
;;; Visual Fill Column Width Configuration

;; Customizable variables
(defvar jc/vfc-prog-mode-width 110
  "Visual fill column width for programming modes.")

(defvar jc/vfc-text-mode-width 80
  "Visual fill column width for text modes.")

(after! visual-fill-column
  ;; Core function
  (defun jc/set-visual-fill-column-width ()
    "Set `visual-fill-column-width' based on current major mode.
Uses `jc/vfc-prog-mode-width' for prog-mode derivatives and
`jc/vfc-text-mode-width' for text-mode derivatives."
    (setq-local visual-fill-column-width
                (cond
                 ((derived-mode-p 'prog-mode) jc/vfc-prog-mode-width)
                 ((derived-mode-p 'text-mode) jc/vfc-text-mode-width)
                 (t visual-fill-column-width))))

  ;; Hook configuration
  (add-hook 'prog-mode-hook #'jc/set-visual-fill-column-width)
  (add-hook 'text-mode-hook #'jc/set-visual-fill-column-width)

;; Center text configuration
(setq visual-fill-column-center-text nil))

;; Map the visual mode toggle (outside the after! block)
(map! :leader
      ;; remapping this as I don't use it that much
      :desc "visible mode"            "t V" #'visible-mode
      ;; assigning this to my more used visible-fill-column-mode
      :desc "visual fill column"      "t v" #'visual-fill-column-mode)
#+end_src

* org
** some org configs for better behavior and usage
#+begin_src emacs-lisp
(after! org
  (setq
   ;; tag alignment
   ;; this value allows for modern themes and column fill to work well together.
   org-auto-align-tags t
   org-tags-column -80
   ;; org fold - edit in an invisible region
   org-fold-catch-invisible-edits 'show-and-error
   ;; C-a and C-e will move the cursor just the heading. No todo keyworks, no tags
   org-special-ctrl-a/e t
   ;; insert new heading after the current subtree
   org-insert-heading-respect-content t
   ;; we can close parent tasks even if successors are still open
   org-enforce-todo-dependencies nil
   ))
   #+end_src

** org-id
To create and use internal valid and unique links in org-mode, we will use the =org-id= features.
#+begin_src emacs-lisp
(after! org
  ;; org-id are globally unique UUIDs
  (setq org-id-method 'uuid)
  ;; It will use the CUSTOM_ID, if it exists
  ;;or will create a new one in the form or UUID, as seen above
  (setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
  ;; file to store the local =org-id= locations
  ;; This way is synced to all my computers
  (setq org-id-locations-file (expand-file-name "org-id-locations" my-data-dir)))
#+end_src

** Completion notes in to the Logbook
Change notes are stored in the node's drawer, so we can fold it conveniently.
#+begin_src emacs-lisp
(after! org
  (setq org-log-into-drawer t))
#+end_src
** Custom states for the tasks
These are the custom states for the tasks, and the character associated to it.

#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords
        '(
          ;; Status for tasks
          (sequence "TODO(t)" "ONGOING(o)" "WAITING(w@/!)" "|" "DONE(d!)" "CANCELED(c@/!)")
          ;; Status for writing
          (sequence "TOWRITE(j)" "TOREVIEW(k@/!)" "REDO(l@/!)" "|" "FINISHED(ñ)" "PURGE(p@/!)"))))
#+end_src
** orgmode Agenda

All the agenda configs

*** Agenda files
We define the agenda files in this variable

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files '(
                           ;; normal task files
                           "~/Nextcloud/agenda/tasks.org"
                           ;; added this one to be able to search in it, and add from here to the main task files.
                           "~/Nextcloud/agenda/someday.org")))
#+end_src

*** icons for the agenda categories
Have some fancy icons for the categories.
#+begin_src emacs-lisp
(after! org
  (customize-set-value
   'org-agenda-category-icon-alist
   `(
     ("calendar" "~/Nextcloud/config/icons/calendar.svg" nil nil :ascent center :mask heuristic)
     ("tasks" "~/Nextcloud/config/icons/check-square.svg" nil nil :ascent center :mask heuristic)
     ("projects" "~/Nextcloud/config/icons/list.svg" nil nil :ascent center :mask heuristic)
     ("financial" "~/Nextcloud/config/icons/dollar-sign.svg" nil nil :ascent center :mask heuristic)
     ("birthdays" "~/Nextcloud/config/icons/heart.svg" nil nil :ascent center :mask heuristic)
     ("revision" "~/Nextcloud/config/icons/shuffle.svg" nil nil :ascent center :mask heuristic)
     ("habits" "~/Nextcloud/config/icons/refresh-ccw.svg" nil nil :ascent center :mask heuristic)
     ("care" "~/Nextcloud/config/icons/heart.svg" nil nil :ascent center :mask heuristic))))
#+end_src

*** Get rid of the DONE tasks in the agenda view
We dont want the cluttering in our views. If a task is done, don't show it on the agenda view.

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-skip-scheduled-if-done t)
  (setq org-agenda-skip-deadline-if-done t)
  (setq org-agenda-skip-timestamp-if-done t))
#+end_src
** TODO Capture templates
Here I will add template captures for doing several things:

#+begin_src emacs-lisp :tangle yes
(after! org
  (setq org-capture-templates'(
                               ;; task related captures
                               ("t" "My TODO task format." entry
                                (file+headline "~/Nextcloud/agenda/tasks.org" "Tasks")
                                "** TODO %i%? %^g\n:PROPERTIES:\n:CATEGORY: tasks\n:END:\n"
                                :empty-lines-after 1)

                               ("p" "New project." entry
                                (file+headline "~/Nextcloud/agenda/tasks.org" "Tasks")
                                "** TODO %? %^g\n:PROPERTIES:\n:COOKIE_DATA: todo recursive\n:CATEGORY: project\n:END:\n"
                                :empty-lines-after 1)

                               ;; Writing related things

                               ;; Everything that I find interesting to create, no matter what it is
                               ("h" "Compost heap" item
                                (file+headline "~/Nextcloud/escritura/retazos/compost_heap.org" "Compost heap")
                                "%i"
                                :empty-lines-after 1)

                               ;; A possible writing idea
                               ("w" "Writing idea." entry
                                (file+headline "~/Nextcloud/escritura/retazos/ideas.org" "Ideas")
                                "** TODO %?\n*** Personajes\n- \n*** Ambientación\n*** Eventos\n"
                                :empty-lines-after 1)

                               ;; An interesenting character
                               ("P" "Personaje" entry
                                (file "~/Nextcloud/escritura/retazos/personajes.org")
                                "* %i%?"
                                :empty-lines-after 1)
                               )))
  #+end_src
** Capture to this buffer
Inspired by https://github.com/ballantony/emacs-writing/blob/main/DoomEmacsWriting.org

Used to capture notes in this file. Useful to maintain notes and snippets separated by projects.
#+begin_src emacs-lisp
(after! org
  (defun my/capture-to-this-buffer ()
    "Capture a note to the current buffer’s file, under the headline \"Notes\")."
    (interactive)
    ;; Make sure we are in an Org buffer.
    (unless (derived-mode-p 'org-mode)
      (user-error "Can’t capture to a non‑Org buffer"))

    ;; Choose the destination that actually exists.
    (let ((target (buffer-file-name)))
      ;; Build a temporary capture template that points at TARGET.
      (let ((org-capture-templates
             `(("t" "Todo"
                entry
                (file+headline ,target "Notes")
                "** TODO %?"))))
        ;; Run the capture UI.
        (org-capture)))))
#+end_src
** Create an org scratch buffer
https://emacs.stackexchange.com/questions/16492/is-it-possible-to-create-an-org-mode-scratch-buffer

When you want to write something fast using org mode, but you don't want to create a new file.

#+begin_src emacs-lisp
(defun my/scratch-org-buffer ()
  "Create a new scratch buffer -- \*hello-world\*"
  (interactive)
  (let ((n 0)
        bufname buffer)
    (catch 'done
      (while t
        (setq bufname (concat "*org-scratch"
                              (if (= n 0) "" (int-to-string n))
                              "*"))
        (setq n (1+ n))
        (when (not (get-buffer bufname))
          (setq buffer (get-buffer-create bufname))
          (with-current-buffer buffer
            (org-mode)
            (insert "# org-scratch buffer\n"))
          ;; When called non-interactively, the `t` targets the other window (if it exists).
          (throw 'done (select-window (display-buffer buffer t))))))))

(map! :leader
      :desc "Open an org scratch buffer"
      "f o" #'my/scratch-org-buffer)
#+end_src
** Refile entries
This lets you choose refiling targets in heading depth of 9, and lets you get also the files in the same directory hierarchy.

#+begin_src emacs-lisp
  ;; all the targets
  (setq org-refile-targets '(
                             (org-agenda-files :maxlevel . 9)
                             ("referencias.org" :maxlevel . 9)
                             ("someday.org" :maxlevel . 9) ;; this is called someday.org now
                             ("~/Nextcloud/escritura/retazos/ideas.org" :maxlevel . 9)))

  (setq org-outline-path-complete-in-steps nil)         ; Refile in a single go
  ;;(setq org-refile-use-outline-path t)                  ; Show full paths for refiling
  (setq org-refile-use-outline-path 'file)                  ; Show full paths for refiling
#+end_src
** custom tags
Create custom tags for different categories and contexts.
#+begin_src emacs-lisp :tangle yes
  (setq org-tag-alist '(
                        ;; Areas of responsibility
                        ("personal" . ?p) ("health" . ?H) ("financial" . ?f)
                        ;; Contexts
                        ("@home" . ?h)  ("@errands" . ?E) ("@computer" . ?c) ("@online" . ?o)  ("@penpaper" . ?P)
                        ;; interests
		        ("emacs" . ?e) ("writing" . ?w) ("reading" . ?r) ("calls" . ?C) ("blog" . ?b)
                        ;; energy
                        ("low_energy" . ?l) ("high_energy" . ?H)
                        )
        )
#+end_src
** reassign org-capture keybinding
I want to have a less complex keybinding for my emacs.
#+begin_src emacs-lisp :tangle yes
(map! :leader
      :desc "org-capture"
      "x" #'org-capture)
#+end_src
** org-journal
This is for journaling every day, if possible.
Documentation can be found here:

https://github.com/bastibe/org-journal

#+begin_src emacs-lisp
;;("C-c r ñ" . org-journal-new-entry)
(use-package! org-journal
  :config
  (setq org-journal-date-prefix "#+TITLE: ")
  (setq org-journal-file-format "%Y-%m-%d.org")
  (setq org-journal-dir (expand-file-name "personal/diario" my-clear-directory))
  (setq org-journal-date-format "%A, %d %B %Y")
  (setq org-journal-encrypt-journal nil)
  )
#+end_src

** Orgmode org-roam config
Org-roam related config.
*** org-roam general configuration

This is a fix for a Debian installation that doesn't allow to connect directly to the sqlite backend. As seen here: https://github.com/magit/emacsql/blob/main/emacsql-sqlite.el
#+begin_src emacs-lisp
(defun which-linux-distribution ()
  "from lsb_release"
  (interactive)
  (when (eq system-type 'gnu/linux)
    (shell-command-to-string "lsb_release -sd")))

;; (when (string-prefix-p "Debian" (which-linux-distribution))
;;   (use-package sqlite3
;;     :ensure t))
#+end_src

#+begin_src emacs-lisp
  ;; main org-roam config
(use-package! org-roam
  :init
  ;; Create the new directory to store roam notes
  (setq org-roam-directory (file-truename "~/Nextcloud/personal/roam"))
  ;; Location of the roam database
  (setq org-roam-db-location (file-truename "~/Nextcloud/personal/roam/org-roam.db"))
  :config
  ;; provide org-roam completion links outside org files.
  (setq org-roam-completion-everywhere t)
  ;; Ensure the keymap is available
  (require 'org-roam-dailies)
  ;; org-roam export: https://www.orgroam.com/manual.html#org_002droam_002dexport
  (require 'org-roam-export)
  ;; autosync
  (org-roam-db-autosync-mode 1))
#+end_src

Open the fleeting notes with a keybinding:
#+begin_src emacs-lisp
;; (defun my/org-roam-fleeting-notes()
;;   "Open my org-roam file with my fleeting notes"
;;   (interactive)
;;   (find-file "~/Nextcloud/personal/roam/fleeting_notes.org"))
;; (global-set-key (kbd "C-c n F") 'my/org-roam-fleeting-notes)
#+end_src

Org-roam capture templates:
#+begin_src emacs-lisp
;; TODO change these paths to variables: we can try concat or expand-file-name
;; org-roam templates
(setq org-roam-capture-templates
      '(
        ;; default template
        ("d" "default" plain
         "* TODO ${title}\n%?"
         :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
         :unnarrowed t)
        ("b" "book notes" plain (file "~/.doom.d/roamtemplates/BookNoteTemplate.org")
         :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: book")
         :unnarrowed t)
        ("w" "writing idea" plain (file "~/.doom.d/roamtemplates/WritingIdea.org")
         :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: writing")
         :unnarrowed t)
        ("c" "writing character" plain (file "~/.doom.d/roamtemplates/CharacterIdea.org")
         :if-new (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n#+filetags: writing character")
         :unnarrowed t)))
#+end_src

Org-roam window configuration and showing:
#+begin_src emacs-lisp
;; How the roam window shows
;; (add-to-list 'display-buffer-alist
;;              '("\\*org-roam\\*"
;;                (display-buffer-in-side-window)
;;                (side . right)
;;                (slot . 0)
;;                (window-width . 0.33)
;;                (window-parameters . ((no-other-window . t)
;;                                      (no-delete-other-windows . t)))))
#+end_src

Search by title and tags:
#+begin_src emacs-lisp
;; To search by title and tags, we will use the information contained here:
;; https://github.com/org-roam/org-roam/pull/2054
(setq org-roam-node-display-template
      (concat "${title:*} "
              (propertize "${tags:20}" 'face 'org-tag)))
#+end_src

*** org-roam UI
I want to check a graphical view of my notes:
#+begin_src emacs-lisp :tangle packages.el
;; org-roam-ui and its dependencies
;; simple httpd
(package! websocket)
(package! simple-httpd)
(package! org-roam-ui)
#+end_src


#+begin_src emacs-lisp :tangle yes
(use-package! org-roam
  :hook (org-roam . org-roam-ui-mode))
#+end_src

#+begin_src emacs-lisp :tangle yes
;; Daily notes for org-roam
;; Directory is relative to org-roam-directory
(setq org-roam-dailies-directory "daily/")


;; Capture template for the dailies
(setq org-roam-dailies-capture-templates
      '(("d" "default" entry
         "* %?"
         :if-new (file+head "%<%Y-%m-%d>.org"
                            "#+title: %<%Y-%m-%d>\n#+filetags: daily\n"))))
#+end_src

*** Restrict agenda to org mode
Functions to isolate the org-roam TODOs from my general agenda.
Extracted from https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html
#+begin_src emacs-lisp
;; I want to get all my org-roam TODOs in the agenda view, but I need to do it only with
;; the files that contain the TODO keywords, and not the whole org-roam directory.

;; https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html

;; we want to load these functions if org-roam is present
(if (not(require 'org-roam nil t))
    ;; if condition
    (message "org-roam not found")
        ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;; else condition

  (setq my/roamtag "roamtag")

  (defun vulpea-buffer-prop-set (name value)
    "Set a file property called NAME to VALUE in buffer file.
      If the property is already set, replace its value."
    (setq name (downcase name))
    (org-with-point-at 1
      (let ((case-fold-search t))
        (if (re-search-forward (concat "^#\\+" name ":\\(.*\\)")
                               (point-max) t)
            (replace-match (concat "#+" name ": " value) 'fixedcase)
          (while (and (not (eobp))
                      (looking-at "^[#:]"))
            (if (save-excursion (end-of-line) (eobp))
                (progn
                  (end-of-line)
                  (insert "\n"))
              (forward-line)
              (beginning-of-line)))
          (insert "#+" name ": " value "\n")))))

  (defun vulpea-buffer-prop-set-list (name values &optional separators)
    "Set a file property called NAME to VALUES in current buffer.
      VALUES are quoted and combined into single string using
      `combine-and-quote-strings'.
      If SEPARATORS is non-nil, it should be a regular expression
      matching text that separates, but is not part of, the substrings.
      If nil it defaults to `split-string-default-separators', normally
      \"[ \f\t\n\r\v]+\", and OMIT-NULLS is forced to t.
      If the property is already set, replace its value."
    (vulpea-buffer-prop-set
     name (combine-and-quote-strings values separators)))

  (defun vulpea-buffer-tags-set (&rest tags)
    "Set TAGS in current buffer.
        If filetags value is already set, replace it."
    (vulpea-buffer-prop-set "filetags" (string-join tags " ")))

  (defun vulpea-buffer-prop-get (name)
    "Get a buffer property called NAME as a string."
    (org-with-point-at 1
      (when (re-search-forward (concat "^#\\+" name ": \\(.*\\)")
                               (point-max) t)
        (buffer-substring-no-properties
         (match-beginning 1)
         (match-end 1)))))


  (defun vulpea-buffer-prop-get-list (name &optional separators)
    "Get a buffer property NAME as a list using SEPARATORS.
          If SEPARATORS is non-nil, it should be a regular expression
          matching text that separates, but is not part of, the substrings.
          If nil it defaults to `split-string-default-separators', normally
          \"[ \f\t\n\r\v]+\", and OMIT-NULLS is forced to t."
    (let ((value (vulpea-buffer-prop-get name)))
      (when (and value (not (string-empty-p value)))
        (split-string-and-unquote value separators))))

  (defun vulpea-buffer-tags-get ()
    "Return filetags value in current buffer."
    (vulpea-buffer-prop-get-list "filetags" " "))

  (defun vulpea-buffer-tags-add (tag)
    "Add a TAG to filetags in current buffer."
    (let* ((tags (vulpea-buffer-tags-get))
           (tags (append tags (list tag))))
      (apply #'vulpea-buffer-tags-set tags)))



  (defun vulpea-project-p ()
    "Return non-nil if current buffer has any todo entry.

              TODO entries marked as done are ignored, meaning the this
              function returns nil if current buffer contains only completed
              tasks."
    (seq-find                                 ; (3)
     (lambda (type)
       (eq type 'todo))
     (org-element-map                         ; (2)
         (org-element-parse-buffer 'headline) ; (1)
         'headline
       (lambda (h)
         (org-element-property :todo-type h)))))

  (defun vulpea-project-update-tag ()
    "Update PROJECT tag in the current buffer."
    (when (and (not (active-minibuffer-window))
               (vulpea-buffer-p))
      (save-excursion
        (goto-char (point-min))
        (let* ((tags (vulpea-buffer-tags-get))
               (original-tags tags))
          (if (vulpea-project-p)
              (setq tags (cons "roamtag" tags))
            (setq tags (remove "roamtag" tags)))

          ;; cleanup duplicates
          (setq tags (seq-uniq tags))

          ;; update tags if changed
          (when (or (seq-difference tags original-tags)
                    (seq-difference original-tags tags))
            (apply #'vulpea-buffer-tags-set tags))))))

  (defun vulpea-buffer-p ()
    "Return non-nil if the currently visited buffer is a note."
    (and buffer-file-name
         (string-prefix-p
          (expand-file-name (file-name-as-directory org-roam-directory))
          (file-name-directory buffer-file-name))))

  (defun vulpea-project-files ()
    "Return a list of note files containing 'roamtag' tag." ;
    (seq-uniq
     (seq-map
      #'car
      (org-roam-db-query
       [:select [nodes:file]
        :from tags
        :left-join nodes
        :on (= tags:node-id nodes:id)
        :where (like tag (quote "%\"roamtag\"%"))]))))




  ;; ---------------------------------
  ;; this is the agenda part

  ;; This will overwrite the current agenda files, and we don't want that
  ;; (defun vulpea-agenda-files-update (&rest _)
  ;;   "Update the value of `org-agenda-files'."
  ;;   (setq org-agenda-files (vulpea-project-files)))

  ;; (defun inject-vulpea-project-files (org-agenda-files)
  ;;   (append org-agenda-files (vulpea-project-files)))
  ;; (advice-add 'org-agenda-files :filter-return #'inject-vulpea-project-files)

  (add-hook 'find-file-hook #'vulpea-project-update-tag)
  (add-hook 'before-save-hook #'vulpea-project-update-tag)

  ;; ;; original code that overwrites the agenda files (using the one above, this one is just for training)
  ;;  (advice-add 'org-agenda :before #'vulpea-agenda-files-update)
  ;;  (advice-add 'org-todo-list :before #'vulpea-agenda-files-update)
  )
#+end_src

Just show the TODOs from org-roam, and not from the general agenda.

#+begin_src emacs-lisp
(defun my/agenda-restrict-to-roam ()
  "Restrict agenda to current project"
  (interactive)
  (let ((org-agenda-files (list org-roam-directory)))
    (org-agenda)))
;;(global-set-key (kbd "C-c n a") 'my/agenda-restrict-to-roam)
#+end_src

*** org-roam random node opening
Opens a random org-roam node.

#+begin_src emacs-lisp
(defun my/random-roam-node ()
  "Opens a random org-roam node."
  (interactive)
  (setq todo-nodes
        (org-roam-db-query
         ;; select the nodes that have the roamtag tag
         [:select [nodes:file]
          :from tags
          :left-join nodes
          :on (= tags:node-id nodes:id)
  	  ]
  	 )
        )
  ;; get a random file from the list and open it
  (find-file (car (nth (random (length todo-nodes)) todo-nodes))))

;; (global-set-key (kbd "C-c n R") 'my/random-roam-node)
#+end_src

Open a random roam node with the roamtag tag (that maps to a TODO entry).
#+begin_src emacs-lisp
(defun my/random-roam-todo-node ()
  "Opens a random org-roam node with the roamtag tag."
  (interactive)
  (setq todo-nodes
        (org-roam-db-query
         ;; select the nodes that have the roamtag tag
         [:select [nodes:file]
          :from tags
          :left-join nodes
          :on (= tags:node-id nodes:id)
          :where (like tag (quote "%\"roamtag\"%"))])
        )
  ;; get a random file from the list and open it
  (find-file (car (nth (random (length todo-nodes)) todo-nodes))))

;; (global-set-key (kbd "C-c n T") 'my/random-roam-todo-node)
#+end_src

* Writing
** english and spanish dictionaries
#+begin_src emacs-lisp :tangle yes
(after! ispell
  (setq ispell-program-name "hunspell")
  (setq ispell-extra-args '("-i" "utf-8"))
  (add-to-list 'ispell-local-dictionary-alist
               '("en_US,es_ES"
                 "[[:alpha:]]" "[^[:alpha:]]" "[']" t
                 ("-d" "en_US,es_ES") nil utf-8))
  (setq ispell-dictionary "en_US,es_ES"))
#+end_src
* Testing

** TODO elfeed and elfeed-org
Configuration for the elfeed and the org files.
#+begin_src emacs-lisp :tangle yes
;; database for elfeed
(use-package! elfeed
  :config
  (elfeed-org)
  (setq elfeed-db-directory (expand-file-name "elfeed/db/" my-data-dir))

  ;; Optionally specify a number of files containing elfeed
  ;; configuration. If not set then the location below is used.
  ;; Note: The customize interface is also supported.
  (setq rmh-elfeed-org-files (list "~/Nextcloud/config/.emacs.d/elfeed/elfeed.org"))
  ;; put the filter to 1 month ago by default
  (setq elfeed-search-set-filter "@1-month-ago")

  ;; open elfeed and update it
  (defun my/elfeed()
    "Opens elfeed and updates it in just a go."
    (interactive)
    (elfeed)
    (elfeed-update)))
#+end_src

* My custom key bindings
This is where I'm going to define my own keybindings.
** Buffer related keybindings
Mapping special keybindings for buffer related functions.

#+begin_src emacs-lisp :tangle yes
(map! :leader
      (:prefix-map ("b" . "buffers")
       :desc "capture to this buffer"  "c"  #'my/capture-to-this-buffer
       :desc "switch to buffer" "b" #'switch-to-buffer
       :desc "kill buffer" "k" #'kill-current-buffer
       :desc "list buffers" "l" #'list-buffers
       :desc "ibuffer" "i" #'ibuffer
       :desc "orgmode scratch buffer" "o" #'my/scratch-org-buffer
       :desc "scratch buffer" "x" #'doom/toggle-scratch-buffer))
#+end_src
** roam related keybindings
Mapping my org roam functions:
- my random roam node
- my random todo roam node
- my agenda restricted to roam

#+begin_src emacs-lisp :tangle yes
(map! :leader
      :desc "random todo roam node"      "n r t" #'my/random-roam-todo-node
      :desc "random roam node"           "n r T" #'my/random-roam-node
      :desc "roam agenda"                "n r a" #'my/agenda-restrict-to-roam)
#+end_src

** Additional keybindings

Online related keybindings
#+begin_src emacs-lisp :tangle yes
(map! :leader
      :desc "eww"      "o b" #'eww
      :desc "elfeed"   "o e" #'my/elfeed)
#+end_src

Outline
#+begin_src emacs-lisp :tangle yes
(map! :leader
      :desc "Search outline"   "s o" #'consult-outline)
#+end_src

* Work environment
This will be my working environment config

#+begin_src emacs-lisp :tangle yes
;; Load this config when using the work computer
(if my-workenvironment-p
    (progn
      (message "loading the work file")
      (org-babel-load-file "~/.doom.d/emacs-org-init-trabajo.org")))
#+end_src
