#+title: doom emacs literate config
#+AUTHOR: Javier Castilla
#+EMAIL: jcastp@pm.me
#+startup: overview
#+language: en

* Summary
This is the literate config for my doom emacs use cases.

I will try to document and compartmentalize the sections, so it's easier to follow up, but it won't always be possible, as some functions overlap, and I'm usually a messy person when speaking of testing.

* General
** variable definition
I define here some very basic variables to configure several parts of the config.

#+begin_src emacs-lisp
(defvar my-config-dir "~/.doom.d/"
  "Personal config directory.")

(defvar my-data-dir "~/Nextcloud/config/.emacs.d/"
  "Personal data directory.")

;; working laptop vm
(defvar my-worksystem-p (equal (system-name) "lubuntuwork")
  "Name of my working machine.")

;; My desktop machine, able to run anything
(defvar my-desktopsystem-p (or
			    (equal (system-name) "olimpo")
			    (equal (system-name) "doomslayer"))
  "Names of my personal machines.")

;; Writing machines
;; probably we can strip some features from them, as they are low end machines
(defvar my-writinglaptop-p (or
			    (equal (system-name) "argos")
			    (equal (system-name) "caliope"))
  "Names of my writing laptops.")

(defvar my-homeenvironment-p (or
			      (string= (getenv "WORKING") "HOME")
			      (not (string= (getenv "WORKING") "WORK")))
  "My home environment predicate.")

(defvar my-workenvironment-p (string= (getenv "WORKING") "WORK")
  "My work environment predicate.")

;; define my clear directory
(defvar my-clear-directory (expand-file-name "Nextcloud_claro/gocryptfs_claro" (getenv "HOME"))
  "My decrupted directory.")

;; check the directory exists
;;(file-directory-p my-clear-directory)

;; check if a directory is a mount point - against "mount" command in the OS.
(defun is-mount-point-p (path)
  "Check if the given PATH is a mount point."
  (let ((mount-output (shell-command-to-string "mount")))
    (string-match (regexp-quote path) mount-output)))

;; This variable will control if my encrypted dir is mounted on the clear directory
(defvar my-clear-directory-is-mounted-p 0
  "My clear directory is correctly mounted - predicate.")

;; Check if the directory is mounted
(if (is-mount-point-p my-clear-directory)
    ;; if it is mounted, we change the variable
    (setq my-clear-directory-is-mounted-p t)
  ;; if it is not mounted, then we should launch the script here
  (progn
    ;; I think we should not launch this from here, but just examine what is wrong in the OS.
    ;;(shell-command "bash ~/Nextcloud/config/mount-encrypted-dirs.sh")
    )
  )
#+end_src

** Personal information
Based on the environment variables.

This uses a special file, not commited, with my personal information, located in the path below.
It contains the variables =user-full-name= and =user-mail-address=
#+begin_src emacs-lisp
;; to protect my personal information, this file is not commited
(load (expand-file-name "Nextcloud/config/.emacs.d/personal_info.el" (getenv "HOME")))
#+end_src
** Start with a maximized frame
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

** Save command history
It is nice to have commands and their history saved so that every time you get back to work, you can just re-run stuff as you need it. It isn't a radical feature, it is just part of a good user experience.

#+begin_src emacs-lisp
(setq savehist-file (expand-file-name "savehist" my-data-dir))
(savehist-mode 1)
(setq history-length t)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history 1)
(setq savehist-additional-variables
      '(kill-ring
        search-ring
        regexp-search-ring)
      )
#+end_src
** auto revert mode
When a file is changed in disk, the buffer reloads to reflect that change.
#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src

Change dired buffers when the directory is changed:
#+begin_src emacs-lisp
;; auto refresh dired when file changes
(add-hook 'dired-mode-hook 'auto-revert-mode)
#+end_src

** Bookmarks
All the config related to the bookmarks.

#+begin_src emacs-lisp
(setq bookmark-default-file (expand-file-name "bookmarks" my-data-dir))
(setq bookmark-save-flag 1)  ;save bookmarks to .emacs.bmk after each entry
#+end_src

** Abbreviation mode
Defines a set of abbreviations that permits complete words with just some characters.

#+begin_src emacs-lisp
;;where do we read the abbrevs from
(setq abbrev-file-name (expand-file-name "abbrev_defs" my-data-dir))
(setq-default abbrev-mode t)
;; save abbrevs when files are saved
(setq save-abbrevs 'silently)
#+end_src

** electric pair mode
To automatically close parenthesis and other punctuation signs.

#+begin_src emacs-lisp
(electric-pair-mode 1)
;; make electric-pair-mode work on more sets of punctuation signs.
(setq electric-pair-pairs
      '(
        (?\¡ . ?\!)
        (?\¿ . ?\?)
        )
      )

(setq electric-pair-inhibit-predicate
      `(lambda (c)
         (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c)))
      )
#+end_src

* UI
** ef-themes
Colorful themes.
https://github.com/protesilaos/ef-themes

#+begin_src emacs-lisp :tangle packages.el
(package! ef-themes
  :recipe (:host gitlab :repo "protesilaos/ef-themes"))
#+end_src

** poet theme
https://github.com/kunalb/poet

#+begin_src emacs-lisp :tangle packages.el
(package! poet
  :recipe (:host github :repo "kunalb/poet"))
#+end_src
** doric themes
https://github.com/kunalb/poet

#+begin_src emacs-lisp :tangle packages.el
(package! doric-themes)
#+end_src


** Time and date
Put time and date on the status line

#+begin_src emacs-lisp
(setq display-time-day-and-date t
      display-time-24hr-format t)
(display-time)
#+end_src

** Open indirect buffer
Open a branch into a different frame, but the same buffer:

#+begin_src emacs-lisp
;; this is done to open the indirect buffer in another window
;; instead on the main one
(use-package! org
  :config
  (setq org-indirect-buffer-display 'other-window)

  (defun my/org-tree-open-in-right-frame ()
    (interactive)
    (org-tree-to-indirect-buffer)
    ;;(windmove-right)
    (other-window 1) ;; to move to the newly generated window
    )
  ;;(global-set-key (kbd "C-c 8" ) 'my/org-tree-open-in-right-frame)
  (map! :leader
        :desc "Open org tree to indirect buffer"
        "b 8" #'my/org-tree-open-in-right-frame)
  )
#+end_src

** Battery management
On laptops it's nice to know how much power you have.

#+begin_src emacs-lisp
(unless (string-match-p "^Power N/A" (battery))
  (display-battery-mode 1)
  )
#+end_src

** Parens mode global
To show matching parens in all the buffers and modes.

#+begin_src emacs-lisp
(show-smartparens-global-mode 1)
#+end_src

** ace-window
To better manage more buffers in screen, as seen here: https://github.com/abo-abo/ace-window

Used in the hydra snippets.
#+begin_src emacs-lisp
(use-package! ace-window
  :config
  (setq aw-scope 'frame)
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
  (global-set-key (kbd "M-o") 'ace-window)
  ;; make the characters bigger, so it is easy to see
  (custom-set-faces
   '(aw-leading-char-face
     ((t (:inherit ace-jump-face-foreground :height 3.0)))))
  )
#+end_src

** beacon
To show the line I am after a long jump.
#+begin_src emacs-lisp :tangle packages.el
(package! beacon
 :recipe (:host github :repo "Malabarba/beacon")
)
#+end_src

#+begin_src emacs-lisp
(use-package! beacon
  :config
  (beacon-mode t)
  (setq beacon-push-mark 35
        beacon-blink-duration 0.5
        beacon-blink-delay 0.5
        beacon-blink-when-focused t
        beacon-color "deep sky blue")
    )
#+end_src

** dimmer
I want to differentiate the window I'm working with.

#+begin_src emacs-lisp :tangle packages.el
(package! dimmer
  :recipe (:host github :repo "gonewest818/dimmer.el"))
#+end_src

#+begin_src emacs-lisp
(dimmer-configure-which-key)
(dimmer-mode t)
(dimmer-configure-magit)
(dimmer-configure-org)

;; configure the dimmer
(setq dimmer-adjustment-mode :both)
(setq dimmer-fraction 0.3)
#+end_src

** Font size increase/decrease
Increase or decrease the font size
#+begin_src emacs-lisp
(global-set-key (kbd "M-+") 'text-scale-increase)
(global-set-key (kbd "M--") 'text-scale-decrease)
#+end_src

* Navigation
** imenu-list
Better menus list

#+begin_src emacs-lisp :tangle packages.el
(package! imenu-list
  :recipe (:host github :repo "bmag/imenu-list"))
#+end_src

#+begin_src emacs-lisp
;; put the imenu in the position we want to
(setq imenu-list-position 'right)
;; Establish the depth of the entries shown
(setq org-imenu-depth 5)
(setq imenu-list-size 0.2)
;; map the keys
;; (global-unset-key (kbd "M-i"))
;;(global-set-key (kbd "C-c s I") #'imenu-list-smart-toggle)
;; Once you open imenu, focus on it
(setq imenu-list-focus-after-activation t)
;; configuring the keybinding as /la/ doom emacs
;; https://rameezkhan.me/posts/2020/2020-07-03--adding-keybindings-to-doom-emacs/
(map! :leader
      :desc "imenu toggle "
      "s I" #'imenu-list-smart-toggle)
#+end_src

** avy-goto-line config
I want to map the =avy-goto-line= to one of the key mapping in doom emacs.
#+begin_src emacs-lisp :tangle yes
(map! :leader
      :desc "avy-goto-line"
      "s l" #'avy-goto-line)
#+end_src
* Org config

** some org configs for better behavior and usage
#+begin_src emacs-lisp
(use-package! org
  :config
  (setq
   ;; tag alignment
   ;; this value allows for modern themes and column fill to work well together.
   org-auto-align-tags t
   org-tags-column 0
   ;; org fold - edit in an invisible region
   org-fold-catch-invisible-edits 'show-and-error
   ;; C-a and C-e will move the cursor just the heading. No todo keyworks, no tags
   org-special-ctrl-a/e t
   ;; insert new heading after the current subtree
   org-insert-heading-respect-content t
   ))
#+end_src

** org-id
To create and use internal valid and unique links in org-mode, we will use the =org-id= features.
#+begin_src emacs-lisp
(use-package! org
  :config
  ;; org-id are globally unique UUIDs
  (setq org-id-method 'uuid)
  ;; It will use the CUSTOM_ID, if it exists
  ;;or will create a new one in the form or UUID, as seen above
  (setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
  ;; file to store the local =org-id= locations
  ;; This way is synced to all my computers
  (setq org-id-locations-file (expand-file-name "org-id-locations" my-data-dir)))
#+end_src

** Custom states for the tasks
These are the custom states for the tasks, and the character associated to it.

#+begin_src emacs-lisp
(use-package! org
  :config
  (setq org-todo-keywords
        '(
          ;; Status for tasks
          (sequence "TODO(t)" "ONGOING(o)" "WAITING(w@/!)" "|" "DONE(d!)" "CANCELED(c@/!)")
          ;; Status for writing
          (sequence "TOWRITE(j)" "TOREVIEW(k@/!)" "REDO(l@/!)" "|" "FINISHED(ñ)" "PURGE(p@/!)")
          )
        )
  )
#+end_src

** orgmode Agenda

All the agenda configs

*** Agenda files
We define the agenda files in this variable

#+begin_src emacs-lisp
(use-package! org
  :config
  (setq org-agenda-files '(
                           ;; normal task files
                           "~/Nextcloud/agenda/tasks.org"
                           ;; added this one to be able to search in it, and add from here to the main task files.
  			   "~/Nextcloud/agenda/someday.org"
                           )
        )
  )
#+end_src

*** icons for the agenda categories
Have some fancy icons for the categories.
#+begin_src emacs-lisp
(use-package! org
  :config
  (customize-set-value
   'org-agenda-category-icon-alist
   `(
     ("calendar" "~/Nextcloud/config/icons/calendar.svg" nil nil :ascent center :mask heuristic)
     ("tasks" "~/Nextcloud/config/icons/check-square.svg" nil nil :ascent center :mask heuristic)
     ("projects" "~/Nextcloud/config/icons/list.svg" nil nil :ascent center :mask heuristic)
     ("financial" "~/Nextcloud/config/icons/dollar-sign.svg" nil nil :ascent center :mask heuristic)
     ("birthdays" "~/Nextcloud/config/icons/heart.svg" nil nil :ascent center :mask heuristic)
     ("revision" "~/Nextcloud/config/icons/shuffle.svg" nil nil :ascent center :mask heuristic)
     ("habits" "~/Nextcloud/config/icons/refresh-ccw.svg" nil nil :ascent center :mask heuristic)
     ("care" "~/Nextcloud/config/icons/heart.svg" nil nil :ascent center :mask heuristic)
     )
   )
  )
#+end_src

*** Get rid of the DONE tasks in the agenda view
We dont want the cluttering in our views. If a task is done, don't show it on the agenda view.

#+begin_src emacs-lisp
(use-package! org
  :config
  (setq org-agenda-skip-scheduled-if-done t)
  (setq org-agenda-skip-deadline-if-done t)
  (setq org-agenda-skip-timestamp-if-done t)
  )
#+end_src

** export
*** Remove the "validate" link from html exports
#+begin_src emacs-lisp
(use-package! org
  :config
  ;; don't show the "validate" link on org-html exports
  (setq org-html-validation-link nil)
  )
#+end_src

*** Ignore exporting some headlines (just the headlines)
This allows headlines to be ignored in the exports. To do so, the ignore tag (C-c C-c ignore) has to be in the header to be ignored. *We only ignore the headlines, the content is still shown.*

#+begin_src emacs-lisp
(use-package! org
  :config
  (load "~/Nextcloud/config/.emacs.d/vendor/ox-extra/ox-extra.el")
  (require 'ox-extra)
  (ox-extras-activate '(ignore-headlines))
  )
#+end_src

*** Export to Latex
All the latex exports

**** TODO Memoir class for org2latex (complete these options)
memoir is a class used to create beautiful documents.

#+begin_src emacs-lisp
(use-package! org
  :config
  (add-to-list 'org-latex-classes
       '("memoir"
                 "\\documentclass[a4paper,17pt,openright,twoside]{memoir}
  \\usepackage{ucs}
  \\usepackage[utf8]{inputenc}
  \\usepackage[spanish]{babel}
  \\usepackage{fontenc}
  \\usepackage{graphicx}

  \% Para poner notas en los márgenes
  \\usepackage{todonotes}

  \% Para tachar palabras
  \\usepackage[normalem]{ulem}

  \\usepackage{hyperref}
  \\usepackage{parskip}
  \\usepackage{fourier}

  \\renewcommand*\\rmdefault{put}

  \\newcommand{\\fin}{\\plainbreak*{3}}

  % command to add edit notes with tiny size
  \\newcommand{\\edit}[1] {\\todo[inline]{#1}}
  \\newcommand{\\adendo}[1] {\\todo[size=\\tiny]{#1}}

  % Chapter style
   \\chapterstyle{dash}

  % How the page is formatted
    \\pagestyle{Ruled}



                 [NO-DEFAULT-PACKAGES]
                 [NO-PACKAGES]"
                 ("\\part{%s}" . "\\part*{%s}")
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section*{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )
)
#+end_src

**** TODO Memoir_draft class for org2latex (complete these options)
memoir is a class used to create beautiful documents.

#+begin_src emacs-lisp
(use-package! org
  :config
  (add-to-list 'org-latex-classes
       '("memoir_draft"
                 "\\documentclass[a4paper,17pt,draft,openright,twoside]{memoir}
  \\usepackage{ucs}
  \\usepackage[utf8]{inputenc}
  \\usepackage[spanish]{babel}
  \\usepackage{fontenc}
  \\usepackage{graphicx}

  \% Para poner notas en los márgenes
  \\usepackage{todonotes}

  \% Para tachar palabras
  \\usepackage[normalem]{ulem}

  \\usepackage{hyperref}
  \\usepackage{parskip}
  \\usepackage{fourier}

  \\renewcommand*\\rmdefault{put}

  \\newcommand{\\fin}{\\plainbreak*{3}}

  \% command to add edit notes with tiny size
  \\newcommand{\\edit}[1] {\\todo[inline]{#1}}
  \\newcommand{\\adendo}[1] {\\todo[size=\\tiny]{#1}}

  \% Chapter style
  \\chapterstyle{dash}

  \% How the page is formatted
  \\pagestyle{Ruled}





                 [NO-DEFAULT-PACKAGES]
                 [NO-PACKAGES]"
                 ("\\part{%s}" . "\\part*{%s}")
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection*{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection*{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph*{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph*{%s}" . "\\subparagraph*{%s}"))
               )
)
#+end_src

**** TODO Memoir_chapter class for org2latex (complete these options)
Same as memoir class, but it start just with chapters, no "part"

#+begin_src emacs-lisp
(use-package! org
  :config
  (add-to-list 'org-latex-classes
       '("memoir_chapter"
                 "\\documentclass[a4paper,17pt,openright,twoside]{memoir}
  \\usepackage{ucs}
  \\usepackage[utf8]{inputenc}
  \\usepackage[spanish]{babel}
  \\usepackage{fontenc}
  \\usepackage{graphicx}

  \\usepackage{hyperref}
  \\usepackage{parskip}
  \\usepackage{fourier}

  \\renewcommand*\\rmdefault{put}

  \\newcommand{\\fin}{\\plainbreak*{3}}

  % Chapter style
   \\chapterstyle{dash}

  % How the page is formatted
    \\pagestyle{Ruled}



                 [NO-DEFAULT-PACKAGES]
                 [NO-PACKAGES]"

                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section*{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )
)
#+end_src

**** TODO Memoir_chapter_draft class for org2latex (complete these options)
Same as memoir class, but it start just with chapters, no "part"

#+begin_src emacs-lisp
(use-package! org
  :config
  (add-to-list 'org-latex-classes
       '("memoir_chapter_draft"
                 "\\documentclass[a4paper,17pt,draft,openright,twoside]{memoir}
  \\usepackage{ucs}
  \\usepackage[utf8]{inputenc}
  \\usepackage[spanish]{babel}
  \\usepackage{fontenc}
  \\usepackage{graphicx}

  \% Para poner notas en los márgenes
  \\usepackage{todonotes}

  \% Para tachar palabras
  \\usepackage[normalem]{ulem}

  \\usepackage{hyperref}
  \\usepackage{parskip}
  \\usepackage{fourier}

  \\renewcommand*\\rmdefault{put}

  \\newcommand{\\fin}{\\plainbreak*{3}}

  \% command to add edit notes with tiny size
  \\newcommand{\\edit}[1] {\\todo[inline]{#1}}
  \\newcommand{\\adendo}[1] {\\todo[size=\\tiny]{#1}}

  \% Chapter style
  \\chapterstyle{dash}

  \% How the page is formatted
  \\pagestyle{Ruled}





                 [NO-DEFAULT-PACKAGES]
                 [NO-PACKAGES]"

                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection*{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection*{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph*{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph*{%s}" . "\\subparagraph*{%s}"))
               )
)
#+end_src

**** TODO reporting class for org2latex (complete these options)


#+begin_src emacs-lisp
(use-package! org
  :config
  (add-to-list 'org-latex-classes
       '("reporting"
                 "\\documentclass[a4paper,17pt,openright,twoside]{article}
  \\usepackage{ucs}
  \\usepackage[utf8]{inputenc}
  \\usepackage[spanish]{babel}
  \\usepackage{fontenc}
  \\usepackage{graphicx}

  \% Para poner notas en los márgenes
  \\usepackage{todonotes}

  \% Para tachar palabras
  \\usepackage[normalem]{ulem}

  \\usepackage{hyperref}
  \\usepackage{parskip}
  \\usepackage{fourier}

  \\renewcommand*\\rmdefault{put}

  \\newcommand{\\fin}{\\plainbreak*{3}}

  \% command to add edit notes with tiny size
  \\newcommand{\\edit}[1] {\\todo[inline]{#1}}
  \\newcommand{\\adendo}[1] {\\todo[size=\\tiny]{#1}}




                 [NO-DEFAULT-PACKAGES]
                 [NO-PACKAGES]"
                 ("\\part{%s}" . "\\part*{%s}")
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section*{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
               )
)
#+end_src

**** Smart quotes
Add smart quotes for latex

#+begin_src emacs-lisp
(use-package! org
  :config
  (setq org-export-with-smart-quotes t)
  )
#+end_src

** TODO Capture templates
Here I will add template captures for doing several things:

#+begin_src emacs-lisp
  (setq org-capture-templates'(
  			     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
                               ;; task related captures

                               ;; ("i" "Inbox" entry
                               ;;   (file+headline "~/Nextcloud/agenda/tasks.org" "Inbox")
                               ;;   "* TODO %i%? "
                               ;;   :empty-lines-after 1)

  			      ("t" "My TODO task format." entry
                                (file+headline "~/Nextcloud/agenda/tasks.org" "Tasks")
                                "** TODO %i%? \n"
                                  :empty-lines-after 1)

  			     ("p" "New project." entry
                                (file+headline "~/Nextcloud/agenda/tasks.org" "Projects")
                                 "** TODO %? \n :PROPERTIES:\n:COOKIE_DATA: todo recursive\n:END:\n   - Objetivo:"
                                :empty-lines-after 1)

  			     ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
                               ;; Writing related things

  			     ;; Everything that I find interesting to create, no matter what it is
  			     ("h" "Compost heap" item
                                (file+headline "~/Nextcloud/escritura/retazos/compost_heap.org" "Compost heap")
                                 "%i"
                                 :empty-lines-after 1)

  			     ;; A possible writing idea
                               ("w" "Writing idea." entry
                                (file+headline "~/Nextcloud/escritura/retazos/ideas.org" "Ideas")
                                "** TODO %?\n*** Personajes\n- \n*** Ambientación\n*** Eventos\n"
                                :empty-lines-after 1)

                               ;; An interesenting character
                               ("P" "Personaje" entry
                                (file "~/Nextcloud/escritura/retazos/personajes.org")
                                "* %i%?"
                                :empty-lines-after 1)
                               )
        )
  #+end_src


** org-appear
/Hides/ the *emphasis* marks +of+ from orgmode, until you are on them.
#+begin_src emacs-lisp :tangle packages.el
(package! org-appear
  :recipe (:host github
           :repo "awth13/org-appear"))
#+end_src

#+begin_src emacs-lisp
  (use-package org-appear
    :hook (org-mode . org-appear-mode)
    )
#+end_src

* Writing
** org-journal
This is for journaling every day, if possible.
Documentation can be found here:

https://github.com/bastibe/org-journal

#+begin_src emacs-lisp
;;("C-c r ñ" . org-journal-new-entry)
(use-package! org-journal
  :config
  (setq org-journal-date-prefix "#+TITLE: ")
  (setq org-journal-file-format "%Y-%m-%d.org")
  ;;(setq org-journal-dir "~/Nextcloud/personal/diario/")
  (setq org-journal-dir (expand-file-name "personal/diario" my-clear-directory))
  (setq org-journal-date-format "%A, %d %B %Y")
  (setq org-journal-encrypt-journal nil)
  )
#+end_src

** Buscar en la RAE
Seach a word in the spanish dictionary.

#+begin_src emacs-lisp
(defun my/buscarae (palabra)
  "Busca una palabra en la RAE."
  (interactive "s¿Qué palabra quieres buscar? ")
  (eww (concat "https://dle.rae.es/" palabra))
  )
#+end_src

** Buscar sinónimos
Seach a synonim.

#+begin_src emacs-lisp
(defun my/sinonimo (palabra)
  "Busca una palabra en un diccionario de sinónimos"
  (interactive "s¿Qué palabra quieres buscar? ")
  (eww (concat "https://www.wordreference.com/sinonimos/" palabra))
  )
#+end_src

** Translate from english
Translate a word

#+begin_src emacs-lisp
(defun my/translate (palabra)
  "Traduccion de inglés a español"
  (interactive "s¿Qué palabra quieres buscar? ")
  (eww (concat "https://www.deepl.com/translator#en/es/" palabra))
  )
#+end_src

* Testing
** TODO elfeed and elfeed-org
Configuration for the elfeed and the org files.
#+begin_src emacs-lisp
;; database for elfeed
(use-package! elfeed
  :config
  (elfeed-org)
  (setq elfeed-db-directory (expand-file-name "elfeed/db/" my-data-dir))

  ;; Optionally specify a number of files containing elfeed
  ;; configuration. If not set then the location below is used.
  ;; Note: The customize interface is also supported.
  (setq rmh-elfeed-org-files (list "~/Nextcloud/config/.emacs.d/elfeed/elfeed.org"))
  ;; put the filter to 1 month ago by default
  (setq elfeed-search-set-filter "@1-month-ago")

  ;; open elfeed and update it
  (defun my/elfeed()
    "Opens elfeed and updates it in just a go."
    (interactive)
    (elfeed)
    (elfeed-update)
    )

  (map! :leader
        :desc "elfeed refresh and UI"
        "d f" #'my/elfeed)

  )
#+end_src

** Nov.el
Read e-pub in emacs.

https://tech.toryanderson.com/2022/11/23/viewing-epub-in-emacs/

#+begin_src emacs-lisp :tangle packages.el
  (package! esxml
    :recipe (:host github :repo "tali713/esxml"))

   (package! nov
     :recipe (:host nil :repo "https://depp.brause.cc/nov.el.git"))
#+end_src


#+begin_src emacs-lisp
(use-package! nov
     :config
     (setq nov-text-width 100)
     ;;(setq nov-text-width t)
     (setq visual-fill-column-center-text t)
     (add-hook 'nov-mode-hook 'visual-line-mode)
     (add-hook 'nov-mode-hook 'visual-fill-column-mode)
     ;; We save the place we left the e-pub in this file:
     (setq nov-save-place-file (expand-file-name "nov-places" my-data-dir))
    (defun my/nov-font-setup ()
      (face-remap-add-relative 'variable-pitch :family "Gentium"
                                :height 1.2))
     (add-hook 'nov-mode-hook 'my/nov-font-setup)
     (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
     )
#+end_src
