#+title: doom emacs config
#+author: Javier Castilla
#+EMAIL: jcastp@pm.me
#+language: en

* original doom config

#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src

#+begin_src emacs-lisp
;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-one)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `after!' block, otherwise Doom's defaults may override your settings. E.g.
;;
;;   (after! PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.
#+end_src
* Summary
This is the literate config for my doom emacs use cases.

I will try to document and compartmentalize the sections, so it's easier to follow up, but it won't always be possible, as some functions overlap, and I'm usually a messy person when speaking of testing.

* General
** variable definition
I define here some very basic variables to configure several parts of the config.

*** Directories used by emacs
#+begin_src emacs-lisp
(defvar my-config-dir "~/.doom.d/"
  "Personal config directory.")

(defvar my-data-dir "~/Nextcloud/config/.emacs.d/"
  "Personal data directory.")
#+end_src

*** Machine names
#+begin_src emacs-lisp
;; working laptop vm
(defvar my-worksystem-p (equal (system-name) "lubuntuwork")
  "Name of my working machine.")

;; My desktop machine, able to run anything
(defvar my-desktopsystem-p (or
			    (equal (system-name) "olimpo")
			    (equal (system-name) "doomslayer"))
  "Names of my personal machines.")

;; Writing machines
;; probably we can strip some features from them, as they are low end machines
(defvar my-writinglaptop-p (or
			    (equal (system-name) "argos")
			    (equal (system-name) "caliope"))
  "Names of my writing laptops.")
#+end_src

*** Environments
#+begin_src emacs-lisp
(defvar my-homeenvironment-p (or
			      (string= (getenv "WORKING") "HOME")
			      (not (string= (getenv "WORKING") "WORK")))
  "My home environment predicate.")

(defvar my-workenvironment-p (string= (getenv "WORKING") "WORK")
  "My work environment predicate.")
#+end_src

*** Encrypted data directories
#+begin_src emacs-lisp
;; define my clear directory
(defvar my-clear-directory (expand-file-name "Nextcloud_claro/gocryptfs_claro" (getenv "HOME"))
  "My decrupted directory.")

;; check the directory exists
;;(file-directory-p my-clear-directory)

;; check if a directory is a mount point - against "mount" command in the OS.
(defun is-mount-point-p (path)
  "Check if the given PATH is a mount point."
  (let ((mount-output (shell-command-to-string "mount")))
    (string-match (regexp-quote path) mount-output)))

;; This variable will control if my encrypted dir is mounted on the clear directory
(defvar my-clear-directory-is-mounted-p 0
  "My clear directory is correctly mounted - predicate.")

;; Check if the directory is mounted
(if (is-mount-point-p my-clear-directory)
    ;; if it is mounted, we change the variable
    (setq my-clear-directory-is-mounted-p t)
  ;; if it is not mounted, then we should launch the script here
  (progn
    ;; I think we should not launch this from here, but just examine what is wrong in the OS.
    ;;(shell-command "bash ~/Nextcloud/config/mount-encrypted-dirs.sh")
    )
  )
#+end_src

** Personal information
Based on the environment variables.

This uses a special file, not commited, with my personal information, located in the path below.
It contains the variables =user-full-name= and =user-mail-address=
#+begin_src emacs-lisp
;; to protect my personal information, this file is not commited
(load (expand-file-name "Nextcloud/config/.emacs.d/personal_info.el" (getenv "HOME")))
#+end_src
** Start with a maximized frame
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src
** undo-tree config
#+begin_src emacs-lisp :tangle yes
;; unmap the C-z keybinding
(global-unset-key (kbd "C-z"))
;; map C-z to undo
(map!
 "C-z" #'undo-tree-visualize)
#+end_src
** Save command history
It is nice to have commands and their history saved so that every time you get back to work, you can just re-run stuff as you need it. It isn't a radical feature, it is just part of a good user experience.

#+begin_src emacs-lisp
(setq savehist-file (expand-file-name "savehist" my-data-dir))
(savehist-mode 1)
(setq history-length t)
(setq history-delete-duplicates t)
(setq savehist-save-minibuffer-history 1)
(setq savehist-additional-variables
      '(kill-ring
        search-ring
        regexp-search-ring)
      )
#+end_src

** recentf
Configure where we save the recent files opened, so I don't loose them once I reinstall doom emacs.
#+begin_src emacs-lisp
;; where to store the recent list file
(after! recentf
  (setq recentf-save-file (expand-file-name "recentf" my-data-dir)))
#+end_src
** persp-save location
#+begin_src emacs-lisp
(use-package! persp-mode
  :config
  (setq persp-save-dir (expand-file-name "persp-confs/" my-data-dir))
)
#+end_src

** auto revert mode
When a file is changed in disk, the buffer reloads to reflect that change.
#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src

** dired config
*** TODO dired omit mode disabled
#+begin_src emacs-lisp :tangle yes
(remove-hook 'dired-mode-hook 'dired-omit-mode)
#+end_src
*** dired hooked to auto revert
Change dired buffers when the directory is changed:
#+begin_src emacs-lisp :tangle yes
;; auto refresh dired when file changes
(add-hook 'dired-mode-hook 'auto-revert-mode)
#+end_src

** Bookmarks
All the config related to the bookmarks.

#+begin_src emacs-lisp
(setq bookmark-default-file (expand-file-name "bookmarks" my-data-dir))
(setq bookmark-save-flag 1)  ;save bookmarks to .emacs.bmk after each entry
#+end_src

** Abbreviation mode
Defines a set of abbreviations that permits complete words with just some characters.

#+begin_src emacs-lisp
;;where do we read the abbrevs from
(setq abbrev-file-name (expand-file-name "abbrev_defs" my-data-dir))
(setq-default abbrev-mode t)
;; save abbrevs when files are saved
(setq save-abbrevs 'silently)
#+end_src

** electric pair mode
To automatically close parenthesis and other punctuation signs.

#+begin_src emacs-lisp
(electric-pair-mode 1)
;; make electric-pair-mode work on more sets of punctuation signs.
(setq electric-pair-pairs
      '(
        (?\¡ . ?\!)
        (?\¿ . ?\?)
        )
      )

(setq electric-pair-inhibit-predicate
      `(lambda (c)
         (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c)))
      )
      #+end_src

* UI
** Time and date
Put time and date on the status line

#+begin_src emacs-lisp
(setq display-time-day-and-date t
      display-time-24hr-format t)
(display-time)
#+end_src

** full path in the title bar
Put the complete path on the title bar, along the filename.

#+begin_src emacs-lisp
(setq-default frame-title-format "%b - (%f)")
#+end_src

** Battery management
On laptops it's nice to know how much power you have.

#+begin_src emacs-lisp
(unless (string-match-p "^Power N/A" (battery))
  (display-battery-mode 1)
  )
#+end_src

** Parens mode global
To show matching parens in all the buffers and modes.

#+begin_src emacs-lisp
(show-smartparens-global-mode 1)
#+end_src

** ace-window
To better manage more buffers in screen, as seen here: https://github.com/abo-abo/ace-window

Used in the hydra snippets.
#+begin_src emacs-lisp
(use-package! ace-window
  :config
  (setq aw-scope 'frame)
  (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
  (global-set-key (kbd "M-o") 'ace-window)
  ;; make the characters bigger, so it is easy to see
  (custom-set-faces
   '(aw-leading-char-face
     ((t (:inherit ace-jump-face-foreground :height 3.0)))))
  )
#+end_src

** dimmer
I want to differentiate the window I'm working with.

#+begin_src emacs-lisp :tangle packages.el
(package! dimmer
  :recipe (:host github :repo "gonewest818/dimmer.el"))
#+end_src

#+begin_src emacs-lisp
;;(dimmer-configure-which-key)
(dimmer-mode t)
(dimmer-configure-magit)
(dimmer-configure-org)

;; configure the dimmer
(setq dimmer-adjustment-mode :both)
(setq dimmer-fraction 0.3)
#+end_src
** Font size increase/decrease
Increase or decrease the font size
#+begin_src emacs-lisp
(global-set-key (kbd "M-+") 'text-scale-increase)
(global-set-key (kbd "M--") 'text-scale-decrease)
#+end_src

** visual fill column
https://github.com/joostkremers/visual-fill-column
This mode restricts the lines up until a set margin, and wraps them logically at that point.

#+begin_src emacs-lisp :tangle yes
(setq visual-fill-column-width 110)
(setq visual-fill-column-center-text t)

;; Map the visual mode toggle
(map! :leader
      ;; remapping this as I don't use it that much
      :desc "visible mode"            "t V" #'visible-mode
      ;; assigning this to my more used visible-fill-column-mode
      :desc "visual fill column"      "t v" #'visual-fill-column-mode
      )
#+end_src

* Navigation
** Movement for paragraphs
Some keys redefined to better adjust to the whole emacs key environment.
#+begin_src emacs-lisp
(global-set-key (kbd "M-p") 'backward-paragraph)
(global-set-key (kbd "M-n") 'forward-paragraph)
#+end_src

** consult-line to C-s
#+begin_src emacs-lisp :tangle yes
(map!
      "C-s" #'consult-line
      "M-y" #'consult-yank-from-kill-ring
      "M-i" #'consult-imenu
      "M-g i" #'consult-imenu-multi
      "M-g h" #'consult-org-heading
      "M-g m" #'consult-mark
      "M-s f" #'consult-find
      "M-s r" #'consult-ripgrep
      )
#+end_src

** avy can select from any window
To make avy able to select from any window in sight. This allows to change from one window to another in just one step.
#+begin_src emacs-lisp :tangle yes
(setq avy-all-windows t)
#+end_src

** Keyboard chords
Shortcuts to commands using just quick key combinations.

#+begin_src emacs :tangle packages.el
(package! key-chord)
#+end_src

#+begin_src emacs-lisp
(use-package! key-chord
  :config
  (key-chord-mode 1)
  ;; Max time delay between two presses of the same key to be considered a key chord.
  ;; Should normally be a little longer than `key-chord-two-keys-delay'.
  (setq key-chord-two-keys-delay 0.1)
  (setq key-chord-one-key-delay 0.2) ; default 0.2
  (key-chord-define-global "ññ" 'eshell)
  (key-chord-define-global "kk" 'other-window)
  (key-chord-define-global "hh" 'ace-window)
  (key-chord-define-global "jj" 'avy-goto-char-2)
  (key-chord-define-global "jk" 'avy-goto-char-timer)
  (key-chord-define-global "jl" 'avy-goto-line)
  ;;(key-chord-define-global "zz" 'undo-tree-visualize)
  ;;(key-chord-define-global "ww" 'hydra-move/body)
  ;;(key-chord-define-global "yy" 'hydra-buffer-mgmt/body)
  )
#+end_src

** imenu-list
Better menus list.

#+begin_src emacs-lisp :tangle packages.el
(package! imenu-list
  :recipe (:host github :repo "bmag/imenu-list"))
#+end_src

#+begin_src emacs-lisp
(after! imenu-list
  ;; put the imenu in the position we want to
  (setq imenu-list-position 'right)
  ;; Establish the depth of the entries shown
  (setq org-imenu-depth 5)
  (setq imenu-list-size 0.2)
  ;; Once you open imenu, focus on it
  (setq imenu-list-focus-after-activation t))

;; configuring the keybinding as /la/ doom emacs
;; https://rameezkhan.me/posts/2020/2020-07-03--adding-keybindings-to-doom-emacs/
(map! :leader
      :desc "imenu toggle"
      "s I" #'imenu-list-smart-toggle)
#+end_src

** avy keyconfig
I want to map the avy jump functions to some doom emacs keybindings.

#+begin_src emacs-lisp :tangle yes
(map! :leader
      (:prefix-map ("j" . "jump")
       :desc "jump to 2 chars"           "j"   #'avy-goto-char-2
       :desc "jump to chars-timer"       "k"   #'avy-goto-char-timer
       :desc "jump to line"              "l"   #'avy-goto-line))
#+end_src

** Open indirect buffer
Open a branch into a different frame, but the same buffer:

#+begin_src emacs-lisp
;; this is done to open the indirect buffer in another window
;; instead on the main one
(use-package! org
  :config
  (setq org-indirect-buffer-display 'other-window)

  (defun my/org-tree-open-in-right-frame ()
    (interactive)
    (org-tree-to-indirect-buffer)
    ;;(windmove-right)
    (other-window 1) ;; to move to the newly generated window
    )
  (global-set-key (kbd "C-c 8" ) 'my/org-tree-open-in-right-frame)
  ;; (map! :leader
  ;;       :desc "Open org tree to indirect buffer"
  ;;       "b 8" #'my/org-tree-open-in-right-frame)
  )
  #+end_src
* Org config
** some org configs for better behavior and usage
#+begin_src emacs-lisp
(after! org
  (setq
   ;; tag alignment
   ;; this value allows for modern themes and column fill to work well together.
   org-auto-align-tags t
   org-tags-column -77
   ;; org fold - edit in an invisible region
   org-fold-catch-invisible-edits 'show-and-error
   ;; C-a and C-e will move the cursor just the heading. No todo keyworks, no tags
   org-special-ctrl-a/e t
   ;; insert new heading after the current subtree
   org-insert-heading-respect-content t
   ;; we can close parent tasks even if successors are still open
   org-enforce-todo-dependencies nil
   ))
   #+end_src

** org-id
To create and use internal valid and unique links in org-mode, we will use the =org-id= features.
#+begin_src emacs-lisp
(after! org
  ;; org-id are globally unique UUIDs
  (setq org-id-method 'uuid)
  ;; It will use the CUSTOM_ID, if it exists
  ;;or will create a new one in the form or UUID, as seen above
  (setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
  ;; file to store the local =org-id= locations
  ;; This way is synced to all my computers
  (setq org-id-locations-file (expand-file-name "org-id-locations" my-data-dir)))
#+end_src

** Completion notes in to the Logbook
Change notes are stored in the node's drawer, so we can fold it conveniently.
#+begin_src emacs-lisp
(after! org
  (setq org-log-into-drawer t))
#+end_src

** Custom states for the tasks
These are the custom states for the tasks, and the character associated to it.

#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords
        '(
          ;; Status for tasks
          (sequence "TODO(t)" "ONGOING(o)" "WAITING(w@/!)" "|" "DONE(d!)" "CANCELED(c@/!)")
          ;; Status for writing
          (sequence "TOWRITE(j)" "TOREVIEW(k@/!)" "REDO(l@/!)" "|" "FINISHED(ñ)" "PURGE(p@/!)"))))
#+end_src

** orgmode Agenda

All the agenda configs

*** Agenda files
We define the agenda files in this variable

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files '(
                           ;; normal task files
                           "~/Nextcloud/agenda/tasks.org"
                           ;; added this one to be able to search in it, and add from here to the main task files.
                           "~/Nextcloud/agenda/someday.org")))
#+end_src

*** icons for the agenda categories
Have some fancy icons for the categories.
#+begin_src emacs-lisp
(after! org
  (customize-set-value
   'org-agenda-category-icon-alist
   `(
     ("calendar" "~/Nextcloud/config/icons/calendar.svg" nil nil :ascent center :mask heuristic)
     ("tasks" "~/Nextcloud/config/icons/check-square.svg" nil nil :ascent center :mask heuristic)
     ("projects" "~/Nextcloud/config/icons/list.svg" nil nil :ascent center :mask heuristic)
     ("financial" "~/Nextcloud/config/icons/dollar-sign.svg" nil nil :ascent center :mask heuristic)
     ("birthdays" "~/Nextcloud/config/icons/heart.svg" nil nil :ascent center :mask heuristic)
     ("revision" "~/Nextcloud/config/icons/shuffle.svg" nil nil :ascent center :mask heuristic)
     ("habits" "~/Nextcloud/config/icons/refresh-ccw.svg" nil nil :ascent center :mask heuristic)
     ("care" "~/Nextcloud/config/icons/heart.svg" nil nil :ascent center :mask heuristic))))
#+end_src

*** Get rid of the DONE tasks in the agenda view
We dont want the cluttering in our views. If a task is done, don't show it on the agenda view.

#+begin_src emacs-lisp
(after! org
  (setq org-agenda-skip-scheduled-if-done t)
  (setq org-agenda-skip-deadline-if-done t)
  (setq org-agenda-skip-timestamp-if-done t))
#+end_src

** TODO Capture templates
Here I will add template captures for doing several things:

#+begin_src emacs-lisp :tangle yes
(after! org
  (setq org-capture-templates'(
                               ;; task related captures

  			       ("t" "My TODO task format." entry
                                (file+headline "~/Nextcloud/agenda/tasks.org" "Tasks")
  			             "** TODO %i%? %^g\n:PROPERTIES:\n:CATEGORY: task\n:END:\n"
                                :empty-lines-after 1)

  			       ("p" "New project." entry
                                (file+headline "~/Nextcloud/agenda/tasks.org" "Tasks")
                                "** TODO %? %^g\n:PROPERTIES:\n:COOKIE_DATA: todo recursive\n:CATEGORY: project\n:END:\n"
                                :empty-lines-after 1)

                               ;; Writing related things

  			       ;; Everything that I find interesting to create, no matter what it is
  			       ("h" "Compost heap" item
                                (file+headline "~/Nextcloud/escritura/retazos/compost_heap.org" "Compost heap")
                                "%i"
                                :empty-lines-after 1)

  			       ;; A possible writing idea
                           ("w" "Writing idea." entry
                                (file+headline "~/Nextcloud/escritura/retazos/ideas.org" "Ideas")
                                "** TODO %?\n*** Personajes\n- \n*** Ambientación\n*** Eventos\n"
                                :empty-lines-after 1)

                           ;; An interesenting character
                           ("P" "Personaje" entry
                                (file "~/Nextcloud/escritura/retazos/personajes.org")
                                "* %i%?"
                                :empty-lines-after 1)
                               )
        )
  )
  #+end_src

** org-ql
https://github.com/alphapapa/org-ql
#+begin_src emacs-lisp :tangle packages.el
(package! org-ql)
#+end_src

** Capture to this buffer
Inspired by https://github.com/ballantony/emacs-writing/blob/main/DoomEmacsWriting.org

Used to capture notes in this file. Useful to maintain notes and snippets separated by projects.
#+begin_src emacs-lisp
(after! org
  (defun my/capture-to-this-buffer ()
    "Capture a note to the current buffer’s file, under the headline \"Notes\")."
    (interactive)
    ;; Make sure we are in an Org buffer.
    (unless (derived-mode-p 'org-mode)
      (user-error "Can’t capture to a non‑Org buffer"))

    ;; Choose the destination that actually exists.
    (let ((target (buffer-file-name)))
      ;; Build a temporary capture template that points at TARGET.
      (let ((org-capture-templates
             `(("t" "Todo"
                entry
                (file+headline ,target "Notes")
                "** TODO %?"))))
        ;; Run the capture UI.
        (org-capture)))))

;; (global-set-key (kbd "C-c C") 'my/capture-to-this-buffer)
#+end_src
