#+TITLE: doom personal config
#+AUTHOR: Javier Castilla
#+EMAIL: jcastp@pm.me
#+startup: overview
#+language: en
* General config
** System information
Variables to conditional load based on systems or locations.

*** based on machine names
Defining variables for conditional execution, based on machines:

#+begin_src emacs-lisp
;; working laptop vm
(defvar my-worksystem-p (equal (system-name) "ESZAR1N1640"))
;; My desktop machine, able to run anything
(defvar my-desktopsystem-p (equal (system-name) "olimpo"))
;; Writing machines, probably we can strip some features
(defvar my-writinglaptop-p
  (or (equal (system-name) "argos") (equal (system-name) "caliope"))
  )
#+end_src

*** based on environment variables
Home and Work environment.

#+begin_src emacs-lisp
(defvar my-workenvironment-p (string= (getenv "WORKING") "WORK"))
(defvar my-homeenvironment-p (string= (getenv "WORKING") "HOME"))
#+end_src

** Personal information
Based on the environment variables.

#+begin_src emacs-lisp
(if (not my-workenvironment-p)
    ;; then part - personal use
    (progn
      (setq user-full-name "Javier Castilla"
            user-mail-address "jcastp@pm.me")
      )
  ;; else part - work use
  (progn
    (setq user-full-name "Francisco Javier Castilla"
          user-mail-address "franciscojavier.castilla@adidas.com")
    )
  )
#+end_src

** Configure the config and data directories
- Config directory contains the files that will be commited. All the files that will get emacs up and running will be here.
- Data directory contains the files that should no be commited, but contains my own information, that is useful.
We will be using this either with concat or expand-file-name:
- expand-file-name for when we have just a filename
- concat for when we have a composite directory and filename, or as a secondary way to do it.
#+begin_src emacs-lisp
;; this is the same as the doom-user-dir
(defvar my-config-dir "~/.doom.d/")
;; where the files I can sync live
(defvar my-data-dir "~/Nextcloud/config/.emacs.d/")
#+end_src

** free-keys
To know which keys are still free.

#+begin_src emacs-lisp :tangle packages.el
(package! free-keys
  :recipe (:host github :repo "Fuco1/free-keys"))
#+end_src

** Bookmarks
All the config related to the bookmarks.

#+begin_src emacs-lisp
;;(setq bookmark-default-file "~/Nextcloud/config/.emacs.d/bookmarks")  ;;define file to use.
(setq bookmark-default-file (expand-file-name "bookmarks" my-data-dir))
(setq bookmark-save-flag 1)  ;save bookmarks to .emacs.bmk after each entry
#+end_src

** Abbreviation mode
Defines a set of abbreviations that permits complete words with just some characters.

#+begin_src emacs-lisp
;;where do we read the abbrevs from
;;(setq abbrev-file-name "~/Nextcloud/config/.emacs.d/abbrev_defs")
(setq abbrev-file-name (expand-file-name "abbrev_defs" my-data-dir))
(setq-default abbrev-mode t)
;; save abbrevs when files are saved
(setq save-abbrevs 'silent)
#+end_src

** electric pair mode
To automatically close parenthesis and and other punctuation signs.

#+begin_src emacs-lisp
(electric-pair-mode 1)
;; make electric-pair-mode work on more sets of punctuation signs.
(setq electric-pair-pairs
      '(
        (?\¡ . ?\!)
        (?\¿ . ?\?)
        )
      )

(setq electric-pair-inhibit-predicate
      `(lambda (c)
         (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c)))
      )
#+end_src

* UI
** Define fonts
Define the fonts for Doom emacs.
There are fixed and variable pitch fonts to define.

#+begin_src emacs-lisp
(setq
  ;; Font used for source code
  ;;doom-font (font-spec :family "JetBrains Mono" :size 14 :weight 'Medium)
  doom-font (font-spec :family "Fira Code" :size 14 :weight 'Medium)
  ;; doom-font (font-spec :family "Hasklig" :size 16 :weight 'Medium)
  ;; doom-font (font-spec :family "Iosevka Fixed" :size 16 :weight 'Medium)
  ;; doom-font (font-spec :family "Hack" :size 14)

  ;; Font used for normal writing
  ;;doom-variable-pitch-font (font-spec :family "Gentium Basic" :size 18)
  ;;doom-variable-pitch-font (font-spec :family "ETBookOT" :size 18)
  ;;doom-variable-pitch-font (font-spec :family "ETBembo" :size 18)

  ;;;; When you want to have a fixed font for the variable one
  doom-variable-pitch-font (font-spec :family "Fira Code" :size 14 :weight 'Medium)
  ;;doom-variable-pitch-font (font-spec :family "JetBrains Mono" :size 16 :weight 'Extralight)
  ;;doom-variable-pitch-font (font-spec :family "JetBrains Mono" :size 18 :weight 'Light)
  ;;doom-variable-pitch-font (font-spec :family "Iosevka" :size 26 :weight 'Regular)
  ;;doom-variable-pitch-font (font-spec :family "Iosevka")
  )
#+end_src

For when I want mixed pitch mode in org mode.

#+begin_src emacs-lisp
;;(add-hook! 'org-mode-hook #'mixed-pitch-mode)
#+end_src

** fontaine
I can change the fonts with just a single command.
https://protesilaos.com/emacs/fontaine

#+begin_src emacs-lisp :tangle packages.el
(package! fontaine
  :recipe (:host github :repo "protesilaos/fontaine"))
#+end_src

Here will come the code for the fontaine package.
#+begin_src emacs-lisp
(after! fontaine
(setq fontaine-presets
      '(
        ;; daily operations, same config as normal config
        (regular
         :default-family "Fira Code"
         :default-weight normal
         :default-height 110
         :fixed-pitch-family "Fira Code"
         :fixed-pitch-weight Medium ; falls back to :default-weight
         :fixed-pitch-height 110
         :variable-pitch-family "Fira Code"
         :variable-pitch-weight normal
         :variable-pitch-height 110
         :bold-family nil ; use whatever the underlying face has
         :bold-weight bold
         :italic-family "Iosevka"
         :italic-slant italic
         :line-spacing 1
         )
        ;; Bigger face for variable width, so I can focus on it
        (writing
         :default-family "EB Garamond"
         :default-weight normal
         :default-height 150
         :fixed-pitch-family "Iosevka"
         :fixed-pitch-weight Medium ; falls back to :default-weight
         :fixed-pitch-height 110
         :variable-pitch-family "ETBembo"
         :variable-pitch-weight Medium
         :variable-pitch-height 200
         :bold-family nil ; use whatever the underlying face has
         :bold-weight bold
         :italic-family "EB Garamond"
         :italic-slant italic
         :line-spacing 1
         )
        ;; change the variable width face to have a different view when editing
        (editing
         :default-family "Iosevka"
         :default-weight normal
         :default-height 130
         :fixed-pitch-family "Iosevka"
         :fixed-pitch-weight nil ; falls back to :default-weight
         :fixed-pitch-height 110
         :variable-pitch-family "Gentium"
         :variable-pitch-weight normal
         :variable-pitch-height 180
         :bold-family nil ; use whatever the underlying face has
         :bold-weight bold
         :italic-family "Iosevka"
         :italic-slant italic
         :line-spacing 1
         )
        ;; change the variable width face to have a different view when editing
        (variable-width
         :default-family "Fira Code"
         :default-weight normal
         :default-height 130
         :fixed-pitch-family "Iosevka"
         :fixed-pitch-weight nil ; falls back to :default-weight
         :fixed-pitch-height 110
         :variable-pitch-family "ETBembo"
         :variable-pitch-weight normal
         :variable-pitch-height 180
         :bold-family nil ; use whatever the underlying face has
         :bold-weight bold
         :italic-family "Iosevka"
         :italic-slant italic
         :line-spacing 1
         )
        ;; For when I want to go back to all fixed width
        (fixed-width
         :default-family "Iosevka"
         :default-weight normal
         :default-height 130
         :fixed-pitch-family "Iosevka"
         :fixed-pitch-weight Medium ; falls back to :default-weight
         :fixed-pitch-height 110
         :variable-pitch-family "Iosevka"
         :variable-pitch-weight Medium
         :variable-pitch-height 130
         :bold-family nil ; use whatever the underlying face has
         :bold-weight bold
         :italic-family "Iosevka"
         :italic-slant italic
         :line-spacing 1

         )
        )
      )
)
#+end_src

** ef-themes
Colorful themes.
https://github.com/protesilaos/ef-themes

#+begin_src emacs-lisp :tangle packages.el
(package! ef-themes
  :recipe (:host gitlab :repo "protesilaos/ef-themes"))
#+end_src
** poet theme
https://github.com/kunalb/poet

#+begin_src emacs-lisp :tangle packages.el
(package! poet
  :recipe (:host github :repo "kunalb/poet"))
#+end_src

** Initial theme
We establish the initial theme.

#+begin_src emacs-lisp
(consult-theme 'leuven)
#+end_src

** full path in the title bar
Put the complete path on the title bar, along the filename.

#+begin_src emacs-lisp
(setq-default frame-title-format "%b - (%f)")
#+end_src

** Time and date
Put time and date on the status line

#+begin_src emacs-lisp
(setq display-time-day-and-date t
      display-time-24hr-format t)
(display-time)
#+end_src

** Open indirect buffer
Open a branch into a different frame, but the same buffer:

#+begin_src emacs-lisp
;; this is done to open the indirect buffer in another window
;; instead on the main one
(after! org
  (setq org-indirect-buffer-display 'other-window)

  (defun my/org-tree-open-in-right-frame ()
    (interactive)
    (org-tree-to-indirect-buffer)
    (windmove-right)
    )
  ;;(global-set-key (kbd "C-c 8" ) 'my/org-tree-open-in-right-frame)
  )
#+end_src

** Battery management
On laptops it's nice to know how much power you have.

#+begin_src emacs-lisp
(unless (string-match-p "^Power N/A" (battery))
  (display-battery-mode 1)
  )
#+end_src

** Long lines get wrapped
Long lines get wrapped when they reach the edge. We activate it for all the buffers.

#+begin_src emacs-lisp
;; 1 for on, 0 for off.
(global-visual-line-mode 1)
#+end_src

** Fill column mode
We want to use the visual fill column mode to limit the width of the lines, even if they don't reach the right edge.

When reaching the established width defined, the line will wrap, even before getting into the right border of the application.

#+begin_src emacs-lisp :tangle packages.el
(package! visual-fill-column
  :recipe (:host codeberg :repo "joostkremers/visual-fill-column"))
#+end_src

#+begin_src emacs-lisp
;; This sets the value to all the buffers, as initially it is a per-buffer variable
(setq-default visual-fill-column-width 100)
;; enable it only for text buffers: org, text, ...
(add-hook 'text-mode-hook 'visual-fill-column-mode)
#+end_src

** Parens mode global
To show matching parens in all the buffers and modes.

#+begin_src emacs-lisp
(show-smartparens-global-mode 1)
#+end_src

* Navigation
** Uniquify
When several buffers visit identically-named files, Emacs must give the buffers distinct names. The usual method for making buffer names unique adds ‘<2>’, ‘<3>’, etc. to the end of the buffer names (all but one of them).

The forward naming method includes part of the file's directory name at the beginning of the buffer name
https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html

#+begin_src emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
#+end_src

** imenu-list
Better menus list

#+begin_src emacs-lisp :tangle packages.el
(package! imenu-list
  :recipe (:host github :repo "bmag/imenu-list"))
#+end_src

#+begin_src emacs-lisp
;; put the imenu in the position we want to
(setq imenu-list-position 'right)
;; Establish the depth of the entries shown
(setq org-imenu-depth 5)
;; map the keys
(global-unset-key (kbd "M-i"))
;;(global-set-key (kbd "C-c s I") #'imenu-list-smart-toggle)
;; Once you open imenu, focus on it
(setq imenu-list-focus-after-activation t)
#+end_src
